# Generated by Django 5.1 on 2024-08-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0004_alter_loggers_wiki"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggers",
            name="icon_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
