# Generated by Django 5.1 on 2024-08-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0005_alter_loggers_icon_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployments",
            name="deployment_name",
            field=models.CharField(default="to-be-replaced"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recordings",
            name="id",
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
