# Generated by Django 5.1 on 2024-08-29 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0008_files_metadata"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="animaldeployments",
            table="Animal_Deployments",
        ),
        migrations.AlterModelTable(
            name="animals",
            table="Animals",
        ),
        migrations.AlterModelTable(
            name="deployments",
            table="Deployments",
        ),
        migrations.AlterModelTable(
            name="files",
            table="Files",
        ),
        migrations.AlterModelTable(
            name="loggers",
            table="Loggers",
        ),
        migrations.AlterModelTable(
            name="loggerswiki",
            table="Logger_Wikis",
        ),
        migrations.AlterModelTable(
            name="mediaupdates",
            table="Media_Updates",
        ),
        migrations.AlterModelTable(
            name="recordings",
            table="Recordings",
        ),
    ]
