# Generated by Django 5.1.1 on 2024-09-06 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0013_remove_files_config_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="files",
            name="file_path",
        ),
    ]
