services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ${HOST_DELTA_LAKE_PATH}:${CONTAINER_DELTA_LAKE_PATH}
      - ${HOST_FILE_STORAGE_PATH}:${CONTAINER_FILE_STORAGE_PATH}
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    volumes:
      - ${POSTGRES_LOCAL_DATA_MOUNT}:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  prefect:
    build:
      context: ./prefect
    ports:
      - "4200:4200"
    env_file:
      - .env
    volumes:
      - ${LOCAL_DATA_PATH}:${CONTAINER_DATA_PATH}

  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ${LOCAL_DATA_PATH}:${CONTAINER_DATA_PATH}
      - ./services:/app/services
      - ./server:/app/server
    depends_on:
      - postgres
