services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ${HOST_DELTA_LAKE_PATH}:/data/delta-lake
      - ${HOST_FILE_STORAGE_PATH}:/data/files
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - HOST_DELTA_LAKE_PATH=/data/
      - HOST_FILE_STORAGE_PATH=/data/
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=divedb
      - POSTGRES_USER=divedbuser
      - POSTGRES_PASSWORD=divedbpassword
      - POSTGRES_PORT=5432
    volumes:
      - ${POSTGRES_LOCAL_DATA_MOUNT}:/var/lib/postgresql/data
    env_file:
      - .env 