from setuptools import setup, find_packages

setup(
    name="DiveDB",
    version="0.1.0",
    packages=find_packages(where="."),
    package_dir={"": "."},
    include_package_data=True,
    install_requires=[
        "black",
        "deltalake",
        "django",
        "duckdb",
        "edfio",
        "flake8",
        "importlib-metadata==4.8.3",
        "load_dotenv",
        "mne",
        "notion_client",
        "pandas",
        "pre-commit",
        "psycopg2-binary",
        "pyarrow",
        "pyedflib",
        "pylint-django",
        "pytest",
        "pytest-django",
        "pytest-recording",
        "python-keystoneclient",
        "python-swiftclient",
        "setuptools",
        "tqdm",
    ],
    url="https://github.com/ecophysviz-lab/DiveDB",
)
