c.NotebookApp.token = ''
c.NotebookApp.password = ''
c.NotebookApp.open_browser = True
c.NotebookApp.ip = '0.0.0.0'
c.NotebookApp.allow_root = True
c.NotebookApp.allow_remote_access = True
c.NotebookApp.allow_origin = '*'
c.NotebookApp.trust_xheaders = True
# c.NotebookApp.default_url = "lab"
c.NotebookApp.base_url = "jupyter"
