# Generated by Django 5.1 on 2024-08-16 19:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animals",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("project_id", models.TextField()),
                ("common_name", models.TextField()),
                ("scientific_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Deployments",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("rec_date", models.DateField()),
                ("animal", models.TextField()),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("start_time_precision", models.TextField(blank=True, null=True)),
                ("timezone", models.TextField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extension", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("media", "Media"), ("data", "Data")], max_length=5
                    ),
                ),
                ("config_metadata", models.JSONField(blank=True, null=True)),
                ("delta_path", models.TextField(blank=True, null=True)),
                ("file_path", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoggersWiki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalDeployments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadata.animals",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadata.deployments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loggers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon_url", models.TextField(blank=True, null=True)),
                ("serial_no", models.TextField(blank=True, null=True)),
                ("manufacturer", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("type_name", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("owner", models.TextField(blank=True, null=True)),
                (
                    "wiki",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadata.loggerswiki",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[("type1", "Type 1"), ("type2", "Type 2")],
                        max_length=10,
                    ),
                ),
                ("update_factor", models.FloatField()),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="metadata.files"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recordings",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("start_time_precision", models.TextField(blank=True, null=True)),
                (
                    "animal_deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadata.animaldeployments",
                    ),
                ),
                (
                    "logger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadata.loggers",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="files",
            name="recording",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="metadata.recordings"
            ),
        ),
    ]
