source .env

kubectl delete secret divedb-credentials

kubectl create secret generic divedb-credentials \
  --from-literal=POSTGRES_DB=$POSTGRES_DB \
  --from-literal=POSTGRES_USER=$POSTGRES_USER \
  --from-literal=POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
  --from-literal=POSTGRES_PORT=$POSTGRES_PORT \
  --from-literal=POSTGRES_HOST=$POSTGRES_HOST \
  --from-literal=DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY \
  --from-literal=OPENSTACK_AUTH_URL=$OPENSTACK_AUTH_URL \
  --from-literal=OPENSTACK_APPLICATION_CREDENTIAL_ID=$OPENSTACK_APPLICATION_CREDENTIAL_ID \
  --from-literal=OPENSTACK_APPLICATION_CREDENTIAL_SECRET=$OPENSTACK_APPLICATION_CREDENTIAL_SECRET \
  --from-literal=OPENSTACK_FILE_STORAGE_CONTAINER_NAME=$OPENSTACK_FILE_STORAGE_CONTAINER_NAME \
  --from-literal=OPENSTACK_USER_ID=$OPENSTACK_USER_ID \
  --from-literal=OPENSTACK_PROJECT_NAME=$OPENSTACK_PROJECT_NAME \
  --from-literal=OPENSTACK_PROJECT_ID=$OPENSTACK_PROJECT_ID \
  --from-literal=AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  --from-literal=AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  --from-literal=AWS_REGION=$AWS_REGION \
  --from-literal=AWS_ENDPOINT_URL=$AWS_ENDPOINT_URL
