# Generated by Django 5.1 on 2024-08-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0002_alter_animaldeployments_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggers",
            name="id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
