# Generated by Django 5.1 on 2024-08-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animaldeployments",
            options={
                "verbose_name": "Animal Deployment",
                "verbose_name_plural": "Animal Deployments",
            },
        ),
        migrations.AlterModelOptions(
            name="animals",
            options={"verbose_name": "Animal", "verbose_name_plural": "Animals"},
        ),
        migrations.AlterModelOptions(
            name="deployments",
            options={
                "verbose_name": "Deployment",
                "verbose_name_plural": "Deployments",
            },
        ),
        migrations.AlterModelOptions(
            name="files",
            options={"verbose_name": "File", "verbose_name_plural": "Files"},
        ),
        migrations.AlterModelOptions(
            name="loggers",
            options={"verbose_name": "Logger", "verbose_name_plural": "Loggers"},
        ),
        migrations.AlterModelOptions(
            name="loggerswiki",
            options={
                "verbose_name": "Logger Wiki",
                "verbose_name_plural": "Logger Wikis",
            },
        ),
        migrations.AlterModelOptions(
            name="mediaupdates",
            options={
                "verbose_name": "Media Update",
                "verbose_name_plural": "Media Updates",
            },
        ),
        migrations.AlterModelOptions(
            name="recordings",
            options={"verbose_name": "Recording", "verbose_name_plural": "Recordings"},
        ),
        migrations.AlterField(
            model_name="animals",
            name="common_name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="animals",
            name="id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="animals",
            name="project_id",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="animals",
            name="scientific_name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="deployments",
            name="animal",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="deployments",
            name="id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="deployments",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("UTC", "UTC"),
                    ("US/Pacific", "US/Pacific"),
                    ("US/Mountain", "US/Mountain"),
                    ("US/Central", "US/Central"),
                    ("US/Eastern", "US/Eastern"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="delta_path",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="files",
            name="extension",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="files",
            name="file_path",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loggers",
            name="icon_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loggers",
            name="manufacturer",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loggers",
            name="owner",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loggers",
            name="serial_no",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loggers",
            name="type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loggers",
            name="type_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recordings",
            name="id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="recordings",
            name="start_time_precision",
            field=models.CharField(
                blank=True,
                choices=[("precise", "Precise"), ("approximate", "Approximate")],
                null=True,
            ),
        ),
    ]
