# Generated by Django 5.1 on 2024-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0006_deployments_deployment_name_alter_recordings_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordings",
            name="name",
            field=models.CharField(default="temp"),
            preserve_default=False,
        ),
    ]
