# Generated by Django 5.1 on 2024-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0007_recordings_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
