# Generated by Django 5.1.1 on 2024-09-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0009_alter_animaldeployments_table_alter_animals_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
