# Generated by Django 5.1.1 on 2024-09-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0011_files_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="file",
            field=models.FileField(default="default", upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
