# Generated by Django 5.1.2 on 2024-10-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0014_remove_files_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="animals",
            name="birth_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animals",
            name="domain_ids",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animals",
            name="lab_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animals",
            name="sex",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="animal_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="animal_age_class",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="arrival_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="departure_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="deployment_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="deployment_location",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="deployment_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="deployment_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="domain_deployment_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="recovery_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="recovery_location",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deployments",
            name="recovery_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loggers",
            name="manufacturer_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loggers",
            name="ptt",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="files",
            name="file",
            field=models.FileField(
                storage="DiveDB.services.utils.storage.OpenStackStorage",
                upload_to="divedb-media/",
            ),
        ),
    ]
