# Generated by Django 5.1.2 on 2024-10-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "metadata",
            "0015_animals_birth_year_animals_domain_ids_animals_lab_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recordings",
            name="attachment_location",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recordings",
            name="attachment_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recordings",
            name="quality",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recordings",
            name="timezone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
