# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: divedb-uploader-data-storage
  labels:
    app: divedb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: rook-ceph-block