apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: divedb-deltalake-pv-claim
  labels:
    app: divedb
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
