apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: divedb-deltalake-cephfs-pv-claim
  labels:
    app: divedb
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
