name: Documentation

on:
  pull_request:

  # Allow workflow to be run manually from the Actions tab:
  workflow_dispatch:

  # Run on main branch when a PR merges down to main
  push:
    tags: ['*']
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Build docs
        working-directory: docs/
        run: |
          make html
      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
